name: DockerHub CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


    - name: Build Backend Image
      run: |
        docker build \
        -t ${{ secrets.DOCKER_USERNAME }}/emp-backend:latest \
        ./backend_flask


    - name: Build Frontend Image
      run: |
        docker build \
        -t ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest \
        ./frontend/frontend


    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/emp-backend:latest


    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest
